In [5]:
import requests 
import pandas as pd 
 
# Fetching data from the provided URL 
url = "http://topic-socialabs.unikomcodelabs.id/topic?keyword=timnas&num_topics=10" 
response = requests.get(url) 
data = response.json() 
 
# Extract context 
context = data['data']['context'] 
 
# Extract documents_topic 
documents_topic = data['data']['documents_topic'] 
 
# Create a DataFrame 
df = pd.DataFrame(documents_topic) 
 
# Add context to each row 
df['context'] = context 
# Saving the DataFrame to a CSV file 
csv_file_path = './timnas-topik-cluster.csv' 
df.to_csv(csv_file_path, index=False) 
 
df

,conversation_id_str,created_at,favorite_count,full_text,id_str,lang,location,probability,quote_count,reply_count,retweet_count,topic,tweet_url,user_id_str,username,in_reply_to_screen_name,image_url,context
0,1800679330726715550,Tue Jun 11 23:59:42 +0000 2024,1,TIMNAS PRIA DAN WANITA MENANG + ERIK TEN HAG STAY,1800679330726715550,in,Indonesia,0.7842922,0,0,0,0,https://x.com/tigapuluhtigax/status/1800679330...,1188470356668895234,tigapuluhtigax,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
1,1800679305925800015,Tue Jun 11 23:59:36 +0000 2024,1,ngerasa ga sih sekarang timnas kalo main pakek...,1800679305925800015,in,"Jombang, Indonesia",0.5271866,0,0,0,0,https://x.com/sotongism/status/180067930592580...,961056397063409664,sotongism,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
2,1800679288326476196,Tue Jun 11 23:59:31 +0000 2024,0,2 Sejarah Dicetak Timnas Indonesia Usai Ganyan...,1800679288326476196,in,NaN,0.930736,0,0,0,0,https://x.com/peanutkacang123/status/180067928...,1464596330421100548,peanutkacang123,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
3,1800589420766355730,Tue Jun 11 23:59:28 +0000 2024,0,@womensfootie_id Tinggal tmbah pemain diaspora...,1800679273185047018,in,NaN,0.7993464,0,0,0,7,https://x.com/PKananku1927/status/180067927318...,1772880651248939008,PKananku1927,womensfootie_id,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
4,1800679270857286043,Tue Jun 11 23:59:27 +0000 2024,0,Timnas Indonesia Vs Timnas Filipina 2-0 Indone...,1800679270857286043,in,NaN,0.9549905,0,0,0,0,https://x.com/kangsil2012/status/1800679270857...,546890263,kangsil2012,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,1800537380392419660,Tue Jun 11 15:56:14 +0000 2024,0,@cingreborn aaak seneng banget guee #timnasday,1800557666047254585,in,NaN,0.84986264,0,0,0,0,https://x.com/kidleaderr/status/18005576660472...,1294225010924466177,kidleaderr,cingreborn,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
1890,1800557640936038793,Tue Jun 11 15:56:08 +0000 2024,0,PREDIKSI TOGEL OREGON 04 12 JUNI 2024 ANGKA MA...,1800557640936038793,in,NaN,0.9666632,0,0,0,8,https://x.com/yupitoto88/status/18005576409360...,1746107999226085376,yupitoto88,NaN,https://pbs.twimg.com/media/GPzdn55aMAA1CUe.png,Berikut adalah kalimat-kalimat utama yang dibu...
1891,1800557615824744466,Tue Jun 11 15:56:03 +0000 2024,0,Timnas menang tapi aku tetep kalah karo dee si...,1800557615824744466,in,NaN,0.9356858,0,0,0,7,https://x.com/Lalalan111111/status/18005576158...,1552276761194274816,Lalalan111111,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
1892,1800557601232691595,Tue Jun 11 15:55:59 +0000 2024,0,buat mas mas belakang gue minta aidrop gol ked...,1800557601232691595,in,NaN,0.57995206,0,1,0,9,https://x.com/celestiaalsky/status/18005576012...,1761777254135394304,celestiaalsky,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...
1893,1800557593167020374,Tue Jun 11 15:55:57 +0000 2024,0,ada yg punya foto bareng pas awal main ga? #Ti...,1800557593167020374,in,bukan akun rp,0.67673516,0,1,0,4,https://x.com/mrshubnerr/status/18005575931670...,1641104358652903425,mrshubnerr,NaN,NaN,Berikut adalah kalimat-kalimat utama yang dibu...

In [ ]:
#filter data by date